version: '3.1'
services:
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        ports:
            - "9000:9000"
            - "9443:9443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - dbPostgres:/var/lib/postgresql/data

volumes:
    portainer_data:
    dbPostgres:
