version: '3.1'

services:
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        restart: always
        ports:
            - "9443:9443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

    postgres:
        image: postgres:latest
        container_name: postgres
        #restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: padawan_api
        ports:
            - "5432:5432"
        volumes:
            - dbPostgres:/var/lib/postgresql/data

    minio:
        image: minio/minio
        container_name: minio
        restart: always
        ports:
            - "9000:9000"
        environment:
            MINIO_ACCESS_KEY: minioadmin
            MINIO_SECRET_KEY: minioadmin
        command: server /data
        volumes:
            - minio_data:/data

volumes:
    portainer_data:
    dbPostgres:
    minio_data:
