version: '3.1'
services:

    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        restart: always
        ports:
            - "9443:9443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
    postgres:
        image: postgres:latest
        container_name: postgres
        #restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: padawan_api
        ports:
            - "5432:5432"
        volumes:
            - dbPostgres:/var/lib/postgresql/data
    
    mongo:
        image: mongo
        container_name: mongo
        #restart: always
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: adminmongo
        volumes:
        - dbmongo:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        #restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_BASICAUTH_USERNAME: root
          ME_CONFIG_BASICAUTH_PASSWORD: adminmongo
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: adminmongo
          ME_CONFIG_MONGODB_URL: mongodb://root:adminmongo@mongo:27017/
       

volumes:
    dbmongo:
    portainer_data:
    dbPostgres:
